### ISSUE TITLE
Typehint error upon retrieving all formats

### ISSUE THREAD

**Issue by kylekz** [Marat555/eventbrite-api-laravel-wrapper#12]
> Argument 1 passed to Marat555\Eventbrite\Factories\HelperEntity\ObjectList::__construct() must be an instance of Marat555\Eventbrite\Factories\HelperEntity\Pagination, null given

`$this->eventbrite->format()->all()`

Changing the [Pagination typehint here](https://github.com/Marat555/eventbrite-api-laravel-wrapper/blob/master/src/Factories/HelperEntity/ObjectList.php#L26) to be nullable works as a fix, but locks you to PHP 7.1, so I figured I'd leave you to decide the route to take.

**Comment by bigdevwhale** [comment]
thank you, fixed
