### ISSUE TITLE
Get event list through Organization ID

### ISSUE THREAD

**Issue by UXandre** [Marat555/eventbrite-api-laravel-wrapper#13]
Hi guys, I've been trying to get an event list through organisation ID with no luck. Can anyone please provide an example? E.g. where can I get the organisation ID and how could we send the request?

Thank you so much!

**Comment by UXandre** [comment]
Just in case somebody faces the same issue - first of all. It's important to understand the Organiser is different from the organisation. According to the Eventbrite API documentation, the default Organisation ID is the user_id if the account doesn't belong to any organisation.

Also, when listing events by Organisation ID instead of using:
`Eventbrite::event()->list('organization', int $organizationId, array $filterParams = []);`

Use the code below with the 's' on the organisation endpoint.
`Eventbrite::event()->list('organizations', int $organizationId, array $filterParams = []);`

May try to submit a PR if this is something valid by the author. Hope this helps.

**Comment by bigdevwhale** [comment]
Hi, @UXandre. Thank you!  I will check your pr today.

**Comment by UXandre** [comment]
> Hi, @UXandre. Thank you! I will check your pr today.

No problem at all Marat! Thanks for building the great library! :)
