### ISSUE TITLE
Not compatible with Laravel 6

### ISSUE THREAD

**Issue by UXandre** [Marat555/eventbrite-api-laravel-wrapper#15]
The package seems not compatible with Laravel 6. Was just wondering if there would be any update on this soon?

**Comment by UXandre** [comment]
Seems to be the version of the illuminate/support package. Maybe we should do:
` "illuminate/support": "~5.1|^6.0"` in the composer.json file? Not 100% sure if this is right as I have never developed a package myself. Just a quick idea after googling around. Thanks!

**Comment by bigdevwhale** [comment]
@UXandre. Thank you! I will check out it today and make fixes if they are needed.

**Comment by UXandre** [comment]
@Marat555 My pleasure!
