### ISSUE TITLE
Filename Error

### ISSUE THREAD

**Issue by garyross** [Marat555/eventbrite-api-laravel-wrapper#22]
The file 
'[eventbrite-api-laravel-wrapper/src/Factories/Entity/AssignedUnit .php](https://github.com/Marat555/eventbrite-api-laravel-wrapper/blob/master/src/Factories/Entity/AssignedUnit%20.php)'
has a space before the extension.

AssignedUnit **SPACE** DOT php

**Comment by bigdevwhale** [comment]
thank you, fixed
